// @bun
function T(s=process.env){return s.LITTLE_CODER_INJECT_MODE==="system"?"system":"message"}function S(s,o,i="",f=process.env){if(!o)return;if(T(f)==="system")return{systemPrompt:i+o};return{message:{customType:s,content:o,display:!1}}}function x(s=process.env){let o=null;return(i)=>{if(T(s)==="system")return!0;if(i===o)return!1;return o=i,!0}}import{existsSync as N,readdirSync as R,readFileSync as A}from"fs";import{join as I,resolve as j}from"path";var O=300,W={edit:["edit","change","modify","update","replace","fix","patch","refactor"],write:["write","create","new file","scaffold","generate file"],read:["read","view","inspect","show file","examine","check content"],grep:["grep","search text","find string","search code","regex"],glob:["glob","find file","list files","file tree","search filename"],shell:["run","command","exec","terminal","bash","sh","test","build"],webfetch:["curl","fetch","http","url","download url","scrape"]};function k(s){if(!s.startsWith("---"))return{data:{},body:s.trim()};let o=s.indexOf(`
---`,3);if(o===-1)return{data:{},body:s.trim()};let i=s.slice(3,o).trim(),f=s.slice(o+4).trim(),l={};for(let d of i.split(`
`)){let c=d.trim();if(!c||c.startsWith("#"))continue;let r=c.indexOf(":");if(r===-1)continue;let e=c.slice(0,r).trim(),t=c.slice(r+1).trim();if(t.startsWith("[")&&t.endsWith("]")){let n=t.slice(1,-1).split(",").map((m)=>m.trim().replace(/^["']|["']$/g,"")).filter(Boolean);l[e]=n;continue}if(t.startsWith('"')&&t.endsWith('"')||t.startsWith("'")&&t.endsWith("'"))t=t.slice(1,-1);if(/^\d+$/.test(t))l[e]=parseInt(t,10);else if(t==="true")l[e]=!0;else if(t==="false")l[e]=!1;else l[e]=t}return{data:l,body:f}}function E(s){let o=s||j(process.cwd(),"skills/tools");if(!N(o))return[];let i=[],f=R(o,{withFileTypes:!0});for(let l of f){if(!l.isFile()||!l.name.endsWith(".md"))continue;let d=I(o,l.name);try{let c=A(d,"utf-8"),{data:r,body:e}=k(c),t=r.target_tool||r.targetTool||"";if(!t)continue;let n=typeof r.token_cost==="number"?r.token_cost:Math.ceil(e.length/4),m=typeof r.priority==="number"?r.priority:10,u=r.name||l.name.replace(/\.md$/,"");i.push({name:u,targetTool:t,tokenCost:n,priority:m,content:e,filePath:d})}catch{}}return i}function b(s,o,i=O){if(s.length===0)return[];let f=[],l=o.lastFailedTool?o.lastFailedTool.toLowerCase():null,d=(o.recentTools||[]).slice(-2).map((n)=>n.toLowerCase()),c=(o.userPrompt||"").toLowerCase(),r=(o.requiredTools||[]).map((n)=>n.toLowerCase());for(let n of s){let m=n.targetTool.toLowerCase(),u=0,a="none";if(r.includes(m))u+=1500,a="required-tool";if(l&&m===l)u+=1000,a="error-recovery";let g=d.lastIndexOf(m);if(g!==-1){let p=400+(g+1)*50;if(p>u)u=p,a="recency";else u+=p}for(let[p,h]of Object.entries(W))if(m===p.toLowerCase()){let w=h.filter((y)=>c.includes(y));if(w.length>0){let y=200+w.length*20;if(y>u)u=y,a="intent";else u+=y}}if(u+=n.priority,u>10)f.push({skill:n,score:u,reason:a})}f.sort((n,m)=>m.score-n.score);let e=[],t=0;for(let n of f)if(t+n.skill.tokenCost<=i)e.push(n.skill),t+=n.skill.tokenCost;return e}function K(s,o=!1){if(s.length===0&&!o)return"";let i=[];if(o)i.push(`### Research Mode Active
When exploring unfamiliar code or errors: read relevant files before proposing modifications.`);for(let f of s)i.push(`### Guidance for ${f.targetTool}
${f.content}`);return i.join(`

`)}import{existsSync as F,readdirSync as B,readFileSync as M}from"fs";import{join as v,resolve as _}from"path";var C=2,D=150,J=300;function L(s){let o=s||[_(process.cwd(),"skills/knowledge"),_(process.cwd(),"skills/protocols")],i=[];for(let f of o){if(!F(f))continue;let l=B(f,{withFileTypes:!0});for(let d of l){if(!d.isFile()||!d.name.endsWith(".md"))continue;let c=v(f,d.name);try{let r=M(c,"utf-8"),{data:e,body:t}=k(r),n=[];if(Array.isArray(e.keywords))n=e.keywords.map((a)=>String(a).trim().toLowerCase());else if(typeof e.keywords==="string")n=e.keywords.split(",").map((a)=>a.trim().toLowerCase()).filter(Boolean);if(Array.isArray(e.triggers))for(let a of e.triggers)n.push(String(a).trim().toLowerCase());if(e.topic)n.push(String(e.topic).trim().toLowerCase());if(e.name)n.push(String(e.name).trim().toLowerCase().replace(/[-_]/g," "));let m=[];if(Array.isArray(e.requires_tools||e.requiresTools))m=(e.requires_tools||e.requiresTools).map((a)=>String(a).trim());else if(typeof(e.requires_tools||e.requiresTools)==="string")m=(e.requires_tools||e.requiresTools).split(",").map((a)=>a.trim()).filter(Boolean);let u=typeof e.token_cost==="number"?e.token_cost:Math.ceil(t.length/4);i.push({name:e.name||d.name.replace(/\.md$/,""),topic:e.topic,keywords:Array.from(new Set(n)),tokenCost:u,requiresTools:m,content:t,filePath:c})}catch{}}}return i}function G(s,o,i=C){if(!o||s.length===0)return[];let f=o.toLowerCase(),l=f.split(/\s+/).filter((c)=>c.length>2),d=[];for(let c of s){let r=0,e=[];for(let t of c.keywords){if(!t)continue;if(f.includes(t))r+=t.includes(" ")||t.startsWith("/")?2.5:1.5,e.push(t);else for(let n of l)if(t===n||t.includes(n)||n.includes(t)){r+=1,e.push(t);break}}if(r>=i)d.push({entry:c,score:r,matchedKeywords:Array.from(new Set(e))})}return d.sort((c,r)=>r.score-c.score),d}function P(s,o,i){let f=i?.threshold??C,l=i?.maxPerEntryTokens??D,d=i?.maxTotalTokens??J,c=G(s,o,f),r=[],e=new Set,t=0;for(let n of c){let m=n.entry.content,u=n.entry.tokenCost;if(u>l){let a=l*4;m=m.slice(0,a)+`
...[truncated to 150 tokens]`,u=l}if(t+u<=d){r.push({...n.entry,tokenCost:u,content:m}),t+=u;for(let a of n.entry.requiresTools)e.add(a)}}return{selected:r,publishedRequiredTools:Array.from(e)}}function q(s){if(s.length===0)return"";return s.map((o)=>`### Protocol / Knowledge: ${o.name}
${o.content}`).join(`

`)}function X(s){let o=null,i=null,f=x(),l=null,d=[],c="";s.on("session_start",()=>{o=null,i=null,l=null,d.length=0,c=""}),s.on("input",async(r)=>{if(typeof r?.text==="string")c=r.text;return{action:"continue"}}),s.on("tool_call",async(r)=>{let e=r?.toolName||r?.tool;if(typeof e==="string"){if(d.push(e),d.length>5)d.shift()}}),s.on("tool_result",async(r)=>{let e=r?.toolName||r?.tool;if(Boolean(r?.isError||r?.error)&&typeof e==="string")l=e;else if(l===e)l=null}),s.on("before_agent_start",async(r)=>{if(!o)o=E();if(!i)i=L();let{selected:e,publishedRequiredTools:t}=P(i,c),n=c.toLowerCase(),m=n.includes("research")||n.includes("investigate")||n.includes("audit")||n.includes("explore codebase"),u=b(o,{lastFailedTool:l,recentTools:d,userPrompt:c,requiredTools:t},300),a=[],g=q(e);if(g)a.push(g);let p=K(u,m);if(p)a.push(p);if(a.length===0)return;let h=a.join(`

`);if(!f(h))return;return S("lc-skill-knowledge-inject",h,r?.systemPrompt)})}export{X as default};
